### ISSUE TITLE
Creating an API Endpoint for Islands

### ISSUE THREAD

**Issue by andreasknoepfle** [andreasknoepfle/treasures.io#38]
In order for the islands to show up in the real application we need a proper JSON endpoint, that renders the islands. 

This should be done within the namespace 
`/api/oceans.json`

Should be the #index method of an OceansController in the Api namespace.

The endpoint should return 4 oceans per default (all generated in place for now).

Resources: 
- Please use: https://github.com/rails-api/active_model_serializers
  Probably we need to get creative, since we do not want to use activerecord yet (it is harder to serialize non-ActiveRecord objects but should still work). I think we can just include ActiveModel in our `Island`: class http://guides.rubyonrails.org/active_model_basics.html#model
https://github.com/silviorelli/active_model_serializers#support-for-poros-and-other-orms (more of a hint but could be outdated)
https://github.com/rails-api/active_model_serializers/blob/v0.10.4/docs/howto/serialize_poro.md (last resort)
- Building APIs with rails: 
  http://apionrails.icalialabs.com/book?utm_source=devfreebooks&utm_medium=medium&utm_campaign=DevFreeBooks
(got this from https://devfreebooks.github.io/, nice source)

**Comment by Joerg-Seitz** [comment]
Moin brauch ich dafür n API module? .. ich hab vorhin irgendwo gelesen, dass wenn die Applikation nurnoch ner WebAPI zuarbeitet und nichtmehr einer Website brauch ich das nichtmehr.. bin etwas verwirrt ^^

**Comment by Joerg-Seitz** [comment]
warum sollte ich die Inseln in json rendern wenn ich einfach ein Ocean-Model erstellen kann und dann 4 davon generiere und die in json render.... Isses nicht viel einfacher wenn ich direkt die ozeane verwende? 

Warum soll ich das active_model_serializer gem  verwenden anstatt das "https://github.com/rails-api/active_model_serializers/blob/v0.10.4/docs/howto/serialize_poro.md (last resort)"  obwohl das viel simpler erscheint.

Wäre cool wenn du bei n paar Aufgaben immer dazuschreibst warum etwas sinnvoll ist.. für mein grundverständins

**Comment by Joerg-Seitz** [comment]
did some changes and uploaded them... please critizise the shit out of them.. it doesnt work and i want to know why ^^

**Comment by andreasknoepfle** [comment]
upload ? where ?

**Comment by andreasknoepfle** [comment]
The Plan is not to use ActiveRecord in the project for now, since SQL-Tables are not a good fit for our data.

I'd like to use either Riak https://github.com/basho/riak-ruby-client or Redis (redis.io) or Cassandra as a persistence layer. 
But Rails (ActiveSupport) provides ActiveModel, which is the Basis for ActiveRecord and should be a nice base, a no mather which persistance layer we use. http://guides.rubyonrails.org/active_model_basics.html

**Comment by Joerg-Seitz** [comment]
iMac-2:treasures.io joerg$ git branch
* JSON-api
  master
iMac-2:treasures.io joerg$ git push
Everything up-to-date
iMac-2:treasures.io joerg$ 


no idea.. why it doesn'T upload the new branch.....

**Comment by Joerg-Seitz** [comment]
pushed it again no idea why it didn'T accept the new branch yesterday
