### ISSUE TITLE
Add some more unit tests for the geometry classes

### ISSUE THREAD

**Issue by andreasknoepfle** [andreasknoepfle/treasures.io#41]
As we wanted to get the island generation branch in as quick as possible we missed out on the unit specs for the geometry classes.

Luckily they are already integration tested, but they should be tested regardlessly, also since the service have a randomness that makes them hard to test. The geometry on the other side should be way easier to test, since the random component is not in there.

**Comment by Joerg-Seitz** [comment]
done check it out in branch more-unit-tests

**Comment by andreasknoepfle** [comment]
cool ... create a Pull-Requests pls then.

**Comment by andreasknoepfle** [comment]
#43
